### ISSUE TITLE
Design workflow of turning survey data into graphable JSON

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#1]
Right now, we're focusing on turning CSVs exported from Qualtrics into JSON that we can visualize.

We need a tool that a non-programmer can use that allows them to upload the CSV exported from Qualtrics and get back a basic visualization in return.

Maybe we need auth, maybe we need additional info from the user that's not in the CSV, maybe the user needs to pick some settings. This is the workflow that needs to be designed before we can start coding anything.

**Comment by himanshichhabra** [comment]
Are you looking for volunteers to work on this project?

**Comment by chaitanyya** [comment]
@himanshichhabra It's an open source project anyone can contribute. Please let me know if there's anything specific you're looking for.

**Comment by himanshichhabra** [comment]
@chaitanyya This is a Gsoc project, that's why was curious to know if anyone can contribute or not.
