### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by kiolalis** [berkmancenter/dotplot#100]
I tried to upload file, both csv or json, but an error appears: "Invalid file type of uploaded file." Maybe my files don't have the proper format. Any help?

**Comment by chaitanyya** [comment]
Dotplot only supports Qualtrics export files as of now.

**Comment by kiolalis** [comment]
Could you please send me an Qualtrics example file, just for testing reasons?

**Comment by chaitanyya** [comment]
We have added some sample data to play around with in the dev branch. Make sure you run the node API and then click on "load sample data" on the dashboard.

**Comment by kiolalis** [comment]
... and something last. Where I can find the <API Endpoint>?

**Comment by kiolalis** [comment]
API endpoint

**Comment by chaitanyya** [comment]
You don't need the endpoint, just spin up the node server and the app will fetch the sample data for you.

**Comment by kiolalis** [comment]
It works. Thanks!
