### ISSUE TITLE
Add Frame modal text changes

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#29]
The title text currently reads: "Create a new frame. Start by selecting single or multiple columns from the list bellow." Let's change it to: "Create a new frame. Start by selecting a survey question below."

Let's change "Column Id" to "Question".

Let's change "Tell us something about the nodes" to "Frame title".

Not text, but let's also change the color of the Create button to something that distinguishes it from the Cancel button.

**Comment by chaitanyya** [comment]
Done in #35.
