### ISSUE TITLE
Transitioning between frames is buggy

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#31]
I don't think storing the node locations for each frame is working correctly. If I create one frame, it looks good. If I create a second frame, that also looks good. If I now click on the first frame, all the nodes jump up to the top left corner.

If I click reset the node positions using the little grid button, I can get positions back, but the nodes often end up in the locations for the other frame if I keep clicking around.

**Comment by chaitanyya** [comment]
Yes, this happens when the d3 force layout is still in the process and you try to change the frame. I've added a progress bar to show when each process ends. How about we disable the transitioning when the layout is still in process?
