### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#38]
I think you're missing nprogress in the bower requirements. I get the following error when serving:

`The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/home/jclark/projects/dotplot/tmp/source_map_concat-input_base_path-2aRCImAD.tmp/0/bower_components/nprogress/nprogress.js'`

**Comment by chaitanyya** [comment]
Fixed in #40
