### ISSUE TITLE
Organize nodes by color

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#54]
When running the force layout to generate node locations, nodes should first move to cluster by color before switching part way through the transition to cluster by foci. This ensures nodes of the same color will be close to one another in the resulting foci. It both makes the graph appear more organized and makes each foci into a rough little pie chart.

**Comment by chaitanyya** [comment]
@jdcc I'll need a little help on this one.

**Comment by arshdkhn1** [comment]
Hi, I would like to work on this feature. Should I start working on this ?

**Comment by chaitanyya** [comment]
@arshdkhn1 Well it's an open source project everyone's free to contribute. But it was mentioned in the guidelines that one should only start contributing after the acceptance of proposal.

**Comment by arshdkhn1** [comment]
@chaitanyya Ohk, I think i missed it. I want to have a little talk about this project, can we talk on irc?

**Comment by chaitanyya** [comment]
@arshdkhn1 I don't use IRC but feel free to drop me a mail.

**Comment by arshdkhn1** [comment]
@chaitanyya Ohk, cool!

**Comment by chaitanyya** [comment]
Done in #68.
