### ISSUE TITLE
Invalid file type or uploaded file

### ISSUE THREAD

**Issue by kiolalis** [berkmancenter/dotplot#63]
I installed dotplot in my pc (windows 10) and when I try to upload either csv or json file the message "invalid file type or uploaded file" appears and I cannot make anything then.
Any help please?
Yannis

**Comment by chaitanyya** [comment]
@kiolalis Can you please share the file with me? Currently DotPlot can only process the Qualtrics export files.

**Comment by kiolalis** [comment]
Thanks for your response. I attached three files. What I have to do in order to make Qualtrics export files?



[csv.zip](https://github.com/berkmancenter/dotplot/files/589126/csv.zip)

**Comment by chaitanyya** [comment]
Sorry for the delayed response. I don't have Qualtrics access so I can't tell you how exactly it works.  I'll surely look into the issue and will get back to you.

**Comment by chaitanyya** [comment]
Only works with Qualtrics export or Dotplot JSON export. Tested and works.
