### ISSUE TITLE
Migration to D3 version 4.

### ISSUE THREAD

**Issue by chaitanyya** [berkmancenter/dotplot#66]

**Comment by jdcc** [comment]
Check out the d3v4 branch. I also made the force layout calculation manual and decoupled from node rendering, which should dramatically improve performance.

**Comment by chaitanyya** [comment]
Thanks @jdcc the force layout works fine, the labels are not showing for some reason.

**Comment by chaitanyya** [comment]
Okay, I've fixed it.

**Comment by jdcc** [comment]
This wasn't clean to merge. I hadn't tested much of anything. It was just an example of getting the force layout to work. If you tested everything else and there were no side effects, great, but just letting you know I didn't review it for other issues.

**Comment by chaitanyya** [comment]
Fixing some of the issues right now.

**Comment by jdcc** [comment]
Done in the refactor.
