### ISSUE TITLE
Have the page respond a bit nicer on smaller screens

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#77]
The bottom options get a little funny when the user's screen gets narrow.

![image](https://user-images.githubusercontent.com/735017/28026272-89c28e32-6563-11e7-9106-d6277f54ea0c.png)

**Comment by chaitanyya** [comment]
Done in [84da16f](https://github.com/berkmancenter/dotplot/commit/84da16fc640969a5d631b914739bd0d47b716dc6)
