### ISSUE TITLE
Show user what to do when first using app

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#78]
The first thing a user sees when they start up the app is "Opps! Looks like..." which could make it sound like they received an error before they even did anything.

A helpful walk-through of the features would be nice, but a first step is changing that "Opps" text to something more helpful - along the lines of "You don't have any data loaded into this project. To do so, click 'Load Data' to the left", or if they have already have data but no frames, "Your project is currently empty. To add a frame, click 'Add Frame' to the left."

That text isn't great, but it should help first time users a bit.

**Comment by chaitanyya** [comment]
Working on a simple "how-to guide" slider at the beginning of the app.

**Comment by chaitanyya** [comment]
Added in [c299d17](https://github.com/berkmancenter/dotplot/commit/1afb644f69a0f6b6d30864dbe70e081c09546bbf)

**Comment by jdcc** [comment]
Why is this an SVG instead of regular HTML?
The font and formatting look pretty wonky in my browser:
![image](https://user-images.githubusercontent.com/735017/28528534-f15c6fd8-705b-11e7-89ba-2e0c70f6c9c1.png)

**Comment by chaitanyya** [comment]
Okay, working on it now. Thanks for reopening the issue.

**Comment by chaitanyya** [comment]
Finished working on it, will push it today or early tomorrow.
