### ISSUE TITLE
Make the expected data format obvious to the user

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#80]
Right now, the UI for loading data just says "Select CSV or JSON file". I uploaded a random CSV to see what would happen, and it gives me the message "CSV successfully parsed," but then nothing else works.

I see two possible solutions to this problem, and we should implement one or both:

1. Add some text to the Load Data modal that explains we only take data from certain sources right now, list those sources, and maybe further explain how to get data CSVs or JSON out of those sources.
2. Make it clear to the user when extracting useful information from the parsed data has failed, i.e., when I upload a random CSV that doesn't fit the expected data format, tell the user that.

**Comment by chaitanyya** [comment]
Done in [84da16f](https://github.com/berkmancenter/dotplot/commit/84da16fc640969a5d631b914739bd0d47b716dc6)
