### ISSUE TITLE
Fix favicon dimensions

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#81]
On my PC, the right and bottom edges of the favicon are cut. Might be neat to make the center transparent instead of white.

![image](https://user-images.githubusercontent.com/735017/28027252-76aa6f42-6566-11e7-922d-f0758d26995a.png)

**Comment by chaitanyya** [comment]
Done in [84da16f](https://github.com/berkmancenter/dotplot/commit/84da16fc640969a5d631b914739bd0d47b716dc6)
