### ISSUE TITLE
DRY up the codebase and make smaller functions

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#86]
There's a lot of duplication in the code base (specifically in `controllers/create.js`). Break out common pieces of code into functions, and make sure each function only does one specific thing. There's a ton to read about this kind of stuff, but [here's](https://blog.codinghorror.com/curlys-law-do-one-thing/) a quick primer.

**Comment by jdcc** [comment]
But wait on this until I merge in the d3v4 changes.

**Comment by chaitanyya** [comment]
Moving all calculations to **utils**.

**Comment by chaitanyya** [comment]
Done for the majority of the `create.js` code, working on `getNodes()` function and `project.js` now.

**Comment by chaitanyya** [comment]
Updated `getNodes()` working on `project.js` now.

**Comment by chaitanyya** [comment]
@jdcc would like your feedback on the code-restructure. Please let me know if I'm following the best practices.

**Comment by jdcc** [comment]
I've done a big ol' refactor on the dev branch. @chaitanyya, take a look. It's not clean yet, but the code base is much simpler now.
