### ISSUE TITLE
Loading sample data failed

### ISSUE THREAD

**Issue by jdcc** [berkmancenter/dotplot#91]
Loading the sample data didn't work for me. I've started the new server app, but I couldn't get the GET request for the sample data to succeed. When I click the button, the console reports `GET http://localhost:3000/projectsampleData 404 (Not Found)`. I also tried `http://localhost:3000/sampleData` and `http://localhost:3000/uploads/sampleData`, which both fail.

**Comment by chaitanyya** [comment]
This I've fixed, will push it today. Thanks for pointing it out.
